---
ID: "9cc009fe-1892-4463-91f4-e742f9c16b61"
Parent: "0f7c442c-7501-43d0-b3bf-5af2b0be68d2"
Template: "0f7c442c-7501-43d0-b3bf-5af2b0be68d2"
Path: /sitecore/templates/Project/testsite1/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240319T170957Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\hvoisine@sidlee.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\hvoisine@sidlee.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f3b95b07-a0d4-4c39-b7cd-676d45f65a2a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\hvoisine@sidlee.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240319T170957Z
